author: "alex"
redis:
  port: 6666
  host: "localhost"
db:
  port: 5432
  host: "localhost"
  user: "username"
  password: "password"
  dbname: "dbname"
mtConfigs:
  - type: MT4
    leverage: 6
  - type: MT5
    leverage: 100
