version: '3.7'

services:
  db:
    image: postgres:13
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: dbname
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'

volumes:
  dbdata:
